#server:
#  port: 8080
#  servlet:
#    context-path: /todolist
#
#spring:
#  datasource:
#    url: "jdbc:mysql://localhost:3306/todolist_db"
#    username: root
#    password: 1
#  jpa:
#    show-sql: true

server:
  port: 8080
  servlet:
    context-path: /todolist

spring:
  datasource:
    url: "jdbc:mysql://mysql:3306/todolist_db"
    username: root
    password: 1
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL8Dialect

